version: '3'

services:
    laravel-app:
      build: .
      ports:
        - "8080:80"
      volumes:
        - ./:/usr/share/nginx
      networks:
        - app-network

    mysql-app:
      image: mysql:5.7.22
      command: --innodb-use-native-aio=0
      ports:
        - "3306:3306"
      volumes:
        - .docker/dbdata:/var/lib/mysql
      environment:
        MYSQL_DATABASE: pusher_jhamas_bd_mysql
        MYSQL_ROOT_PASSWORD: root 
      networks:
        - app-network

    messenger-app:
      build:
        context: node
        dockerfile: Dockerfile
      command: ["npm", "start"]  
      ports:
        - "8890:8890"
      volumes:
        - .:/var/www
      networks:
        - app-network
      
    redis-app:
      image: bitnami/redis:latest
      volumes:
        - .docker/redis-data:/data
      command: ["redis-server", "--appendonly", "yes"]  
      ports:
        - "6379:6379"
      networks:
        - app-network
  
networks:
  app-network:
    driver: bridge
  